<p><?php echo $this->translate('hello', 'ScaledModule');?></p>

<p id="foo" style="background-color:red">Green if javascript was loaded, and layout is set correctly</p>

<p id="bar" style="background-color:red">Green if css was loaded, and layout is set correctly</p>

<p>Below you should see an image of the Sun and Venus</p>
<img src="/images/venuspassage.jpg" alt="You should see a picture here"/>